$ANSIBLE_VAULT;1.1;AES256
65623634363436636262363966623531383933346562613334356433653062653462366538613735
6266353732663934653631386332336664643834656465610a333564373166663934333166613939
31626439326561303865643936333035386364646538323831356638373839383436613561313432
6362313739363863360a396131646439623131646239396133613238313130613230303265643732
32623638613731303265306337623235643135313039313438326432333235623930303634343234
36653936306438393732636462363330343537393163333466653739323061643066306166633465
616363396532313030613735643462643332
