$ANSIBLE_VAULT;1.1;AES256
38313062306139393931623265616665353466313261343239636136396339363066393737653266
3663666363393331373936366236346435376639663264380a333934316561396630356666373465
35333237303633303461333161666635353332366239666534653138326633336364316433626239
3337623064356661630a306366356336303339326539333965623134356339656438383639363939
32343337366561333631386666353665616635666362623464316563333632633062383730333661
38396337353730346234646433323739353362343934306666323637396636643035346435303038
62343266653739616562353964366665386161343231306239633530636638333437396632376463
39623566313838353235336665353431613936336432306535313861343661666264386265643165
65316639643939343939613333633639623662336133336261363938613731383332646235343161
3361333166653636633132353863346430626136336532313166
